# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
    # specify the version you desire here
    - image: circleci/node:12
      user: root

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Install dependencies
          working_directory: ~/repo
          command: |
            whoami && sudo whoami && npm i --unsafe-perm=true cross-env -g && npm i --unsafe-perm=true mhy@2.14.0 -g

      - deploy:
          name: Trigger deployment
          working_directory: ~/repo
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            sh ./ci.sh