# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
    # specify the version you desire here
    - image: circleci/node:12
      environment:
        NPM_CONFIG_PREFIX=/home/circleci/.npm-global
        PATH=$PATH:/home/circleci/.npm-global/bin

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Set stuff
          working_directory: ~/repo
          command: |
            npm i cross-env -g && npm i mhy@latest -g

      - run:
          name: Install dependencies
          working_directory: ~/repo
          command: |
            npm i cross-env -g && npm i mhy@latest -g

      - deploy:
          name: Trigger deployment
          working_directory: ~/repo
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            sh ./ci.sh